repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.45.0
    hooks:
      - id: terraform_fmt
      # - id: terraform_validate
      # - id: terraform_tflint
      # #- id: terraform_tfsec
      # - id: terraform_docs
      # #- id: terrascan
      # - id: infracost_breakdown
      #   args:
      #     - --args=--path=./env/dev
      #     - --hook-config='.totalHourlyCost|tonumber > 0.1'
      #     - --hook-config='.totalHourlyCost|tonumber > 1'
      #     - --hook-config='.projects[].diff.totalMonthlyCost|tonumber != 10000'
      #     - --hook-config='.currency == "USD"'
      # - id: terraform_checkov
      #   args:
      #     - --args=--quiet
      #     - --args=--skip-check CKV_AWS_21
