# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  profile = "ivan-arteaga-dev"
  region  = "eu-west-1"
  default_tags {
    tags = {
      Owner         = "TFGM"
      ProductOwner  = "Ivan Pedro"
      BusinessOwner = "DCS"
      Product       = "secrets"
      Repo          = "secrect"
      Tech          = "terraform"
      Environment   = "root"
    }
  }
}
