FROM golang:alpine AS build
RUN apk add --no-cache git

WORKDIR /app
COPY ./app/. .
RUN go get -u github.com/go-sql-driver/mysql
RUN go mod init main
RUN go list -m all
#RUN go test
#RUN go mod download
# Download all the dependencies
#RUN go get -d -v ./...
# Install the package
#RUN go install -v ./...

RUN go build -o /out .

#final stage
FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=build /out /app

ENTRYPOINT ["./app"]
EXPOSE 8080
