# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  web:
    # build: .
    # command: python /code/manage.py runserver 0.0.0.0:8000

    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env_manual
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:14.3
    env_file:
      - .env_manual
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    ports:
      - 5432:5432

volumes:
  postgres_data:
