version = 0.1
[default.deploy.parameters]
stack_name = "nextjs-zip-dev"
resolve_s3 = true
s3_prefix = "nextjs-zip-dev"
region = "eu-west-1"
profile = "ivan-arteaga-dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
