name: PR workflow

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      region:
        required: true
        type: string
    secrets:
      aws-deployment-role-arn:
        required: true
      git-credentials:
        required: true

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  pr:
    concurrency: ${{ inputs.name }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.name }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws-deployment-role-arn }}
          role-session-name: ${{ github.actor }}-deploy
          aws-region: ${{ inputs.region }}
      - run: git config --global url."https://x-access-token:${{ secrets.git-credentials }}@github.com".insteadOf ssh://git@github.com
      - name: Terraform fmt
        working-directory: ${{ inputs.name }}
        id: fmt
        run: terraform fmt -check
      - name: Terraform Init
        working-directory: ${{ inputs.name }}
        run: terraform init
      - name: Terraform Plan
        working-directory: ${{ inputs.name }}
        id: plan
        run: terraform plan -no-color
